# Page settings

baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "cn"
title = ""
theme = "ali-cv-cn"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "吴航海"
        tagline = "技术领域专家"
        avatar = "avatar.jpg"







    [params.contact]
        enable = true
        location = "成都"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+8618583657638"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "wuhanghai@gmail.com"
        #[[params.contact.list]]
        #icon = "fas fa-globe"
        #url = "#"
        #text = "www.sailing0505.github.io"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "专业技术"
        [[params.skills.list.items]]
        details = "Java/Go/C++/C"
        [[params.skills.list.items]]
        details = "Python/JavaScript/Bash"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL/MongoDB"
        [[params.skills.list.items]]
        details = "Linux/Docker/Kubernetes"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "技能"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "计算机学士学位"
        university = "成都信息工程大学"
        dates = "2001 - 2005"



    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "成都创新之星"
        body = "Nokia, Chengdu"
        date = "2019"

        [[params.awards.list]]
        name = "成都中学创新赛教练自愿者"
        body = "JA 中国"
        date = "2019"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "中文"
        level = "母语"
        [[params.languages.list]]
        name = "English"
        level = "专业"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"


    [params.summary]
        enable = true
        text = "15年（+）通信行业研发背景。先后服务于华为与诺基亚研发中心。 全栈工程师。善于把具体的问题抽象成对应的模型，然后通过软件设计来解决。熟练于软件需求分析到软件交付全流程的计划，执行，与流程控制。Linux极客,熟练操作Linux 桌面与服服务器版本。快速学习者，能在短时间内学习新的技能。同时具备良好的沟通能力，善于倾听以及分享，能够融入团队，与团队共同进步和成长。"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Expert, Domain Expert"
        dates = "2016 - 至今"
        company = "Nokia"
        details = "Nokia网管产品NetAct领域专家。负责产品需求分析，技术落地，原型研究。制定领域相关(system serviceability)产品规划。新技术研究与应用。技术难题攻关。"
       

        [[params.experience.list]]
        title = "Speciallist, Software Engineer"
        dates = "2013 - 2016"
        company = "Nokia"
        details = "Nokia网管产品NetAct高级工程师。主要工作为平台相关的模块开发，测试，文档，运维。领导开发团队进行项目实施。" 

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2008 - 2013"
        company = "Nokia"
        details = "Nokia研发工程师" 

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2005 - 2008"
        company = "HuaWei"
        details = "研发工程师"

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Neo"
        meta = "2021"
        
        tagline = "- 概述\n  - 支持通过NETCONF-YANG协议集成网络设备到新一代网管平台。实现设备集成与告警上报的功能\n- 做了什么\n  - 产品需求分析，方案预研,POC,以及评审,项目计划（KANBAN）\n   - 项目实施（开发，测试，CI）\n  - 微服务集成测试（与印度团队）\n  - 客户文档编写\n- 怎么做\n  - 与产品经理沟通需求后，采用SNAKE方法产出技术文档。并与团队以及项目技术架构团队讨论，确定技术方案。\n  - GO语言快速学习，参与开发与测试\n  - 微服务架构快速学习。使用pact进行服务之间的合约测试，并在团队内部分享与讨论\n  - 与项目经理沟通，把握项目进度，参与集成测试，解决测试中遇到的问题。\n- 思考\n  - 从信息源头开始学习会事半功倍，积极讨论与分享可以激励团队，也能更好掌握学习的内容。\n  - 微服务架构下，服务与服务之间调用关系复杂。用好**pact**合约测试很重要，能够充分保证服务接口版本的兼容性，不会让新增修改污染已存在的用户。"
        
        [[params.projects.list]]
        title = "Netact telecom cloud application"
        meta = "2019-2020"
        tagline = "- 概述\n  - 一个全新的后台服务(Java)。该服务作为NetAct网管系统东西向接口，提供了对CBAM(波兰团队)产品的集成。并满足ETSI规范定义的接口要求。\n- 做了什么\n  - 项目可行性分析，方案的设计与原型实现。\n  - 协助产品经理进行项目立项，澄清阶段需求。\n  - 软件设计方案与评审。\n  - 项目实施。\n- 怎么做\n  - 因为是一个全新的小产品，所以首先需要协助经理进行团队招聘和搭建(10人)。\n  - 与团队成员沟通设计方案，分解开发任务，带领团队进行项目开发工作。\n  - 与测试成员沟通功能用例，设计自动化测试用例。\n  - 与CBAM技术团都沟通交流。解决项目中遇到的问题。\n- 思考\n  - 别过早的纠结细节。\n  - 精简需求，关注阶段最核心问题\n  - 编写自动化测试与开发工作同步进行。\n  - 每个人都需要编码"

        [[params.projects.list]]
        title = "Netact servicability services"
        meta = "2016-2019"
        tagline = "- 概述\n  - 系统的自我管理，包括告警监控，性能监控，问题调试，日志监控，配置监控。\n- 做了什么\n  - 症状收集工具(symptom collector)\n  - 配置文件监控工具(configuration monitor)\n  - 环境监控工具\n  -系统健康检查工具(health check)\n  - 系统自我监控控制台(service monitor UI)\n- 怎么做\n  - 分析系统现存的自监控功能，找到需要改进的薄弱环节\n  - 与技术支持团队沟通，收集需求。并与产品经理整理需求，提取功能点。评估工作量\n  - 根据需求进行软件工具设计\n  - 工具开发,测试，发布。\n  - 制作视频进行培训和宣传\n- 思考\n  - serviceability是所有软件系统的非功能性需求，往往没有具体的规范和定义,通常软件被发现或者上报的缺陷会作为一个平见自管理系统的KPI，往往团队需要对特定的问题进行改进提高客户的满意度。快速，灵活的改进非常重要，有利于提高团队的动力。\n"


        [[params.projects.list]]
        title = "PM platform migration and deliver"
        meta = "2015"
        tagline = "- 概述\n  - 支持海量设备性能数据监控是评价网管系统性能的核心指标。PM 平台是一个相对独立，采用C++语言开发的高效性能监控平台。需要把该软件迁移部署到NetAct生产环境上，并且能够把原有的数据导入到该平台中。该项目由成都研发中心与葡萄牙Aveiro研发中心共同合作。\n- 做了什么\n  - 成都site项目接口人，负责与葡萄牙团队沟通与交流。\n  - 数据迁移方案讨论，相关内容的推动与落地。\n  - 产品交付到葡萄牙团队。\n- 怎么做\n  - 成都团队以前主要负责PM平台组件部分，而葡萄牙团队负责平台上应用部分。首先对平台组件进行裁剪，确定裁剪方案\n  - 搭建编译测试环境，对裁剪后的组件进行编译测试\n  - 根据数据迁移方案，编写数据导入，导出，格式转换脚本\n  - 代表成都研发中心出差葡萄牙，与当地同事共同工作，测试，交付前期内容，并输出培训。\n"


        [[params.projects.list]]
        title = "OSI stack Problem solve taskforce"
        meta = "2010"
        tagline = "- 概述\n  - 系统在连续一周的稳定性测试中发生致命的kernel panic问题。经调查，问题来源于使用一家英国软件供应商提供的OSI协议栈软件。于是成立一个虚拟团队在芬兰坦佩雷进行技术攻关。团队成员（6人）由成都，英国软件供应商，芬兰技术专家组成。\n- 做了什么\n  - 测试问题稳定重现与测试框架优化\n  - 测试数据分析，代码分析。\n  - 解决方案提出。\n- 怎么做\n  - 问题发生在性能稳定性测试中，大量的原始信息丢失。所以首先需要做的是复现问题，并收集相关信息，如日志，tcpdump, Linux kernel trace等。\n  - 性能测试工具优化，提高模拟器性能，引入更加满足真实客户环境的测试数据。\n  - 在攻关过程中，共解决致命问题5个，严重问题20多个。\n"


    [params.information]
        enable = true

        [[params.information.list]]
        title = "创新方案"
        [[params.information.list.items]]
        details = "2019 . 精确的可视化应用程序负载信息"
        [[params.information.list.items]]
        details = "2019 · 自适应应用程序负载系统"
        [[params.information.list.items]]
        details = "2017 · symptom-collector工具自动补全"
        [[params.information.list.items]]
        details = "2015 · 自动登录lab工具"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/sailing0505?tab=repositories"
        title = "sailing0505"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/hanghai-wu-71296118/"
        title = "wuhanghai@gmail.com"
        [[params.social.list]]
        icon = "fab fa-weixin"
        url = "//twitter.com/username"
        title = "18583657638"
