baseURL = "https://sailing0505.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "jason-cv-en"
title = "Example - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
